# Generated by Django 6.0.5 on 2026-05-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_key", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=120)),
                ("content", models.TextField(blank=True)),
                ("fmt", models.CharField(max_length=8)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("provider_key", "name")},
            },
        ),
    ]
