# Generated by Django 6.0.5 on 2026-05-31 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PathOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_key", models.CharField(max_length=64, unique=True)),
                ("path", models.CharField(max_length=1024)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
