# Generated by Django 6.0.5 on 2026-06-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0002_pathoverride"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_key", models.CharField(max_length=64, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "command",
                    models.CharField(
                        default="claude auth status",
                        help_text="CLI command that outputs JSON with login status.",
                        max_length=255,
                    ),
                ),
                (
                    "json_path_email",
                    models.CharField(
                        default="email",
                        help_text="JSON key path for user email (dot-separated, e.g. 'user.email').",
                        max_length=128,
                    ),
                ),
                (
                    "json_path_plan",
                    models.CharField(
                        default="subscriptionType",
                        help_text="JSON key path for plan name.",
                        max_length=128,
                    ),
                ),
                (
                    "json_path_org",
                    models.CharField(
                        blank=True,
                        default="orgName",
                        help_text="JSON key path for organization name (optional).",
                        max_length=128,
                    ),
                ),
                (
                    "json_path_logged_in",
                    models.CharField(
                        default="loggedIn",
                        help_text="JSON key path for boolean login flag.",
                        max_length=128,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
