# Generated by Django 6.0.5 on 2026-07-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_aimodel_tokencheck'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aimodel',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='aimodel',
            name='providers_a_provide_c384d6_idx',
        ),
        migrations.DeleteModel(
            name='AIModel',
        ),
    ]
